// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"GoHomeWork_week3/app/user/service/internal/biz"
)

// Injectors from wire.go:

// InitializeEvent 声明injector的函数签名
func InitializeEvent(msg string) biz.Event {
	message := biz.NewMessage(msg)
	greeter := biz.NewGreeter(message)
	event := biz.NewEvent(greeter)
	return event
}
